apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-k8s-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/shamkumbhar/Jenkins-integration-with-kubernetes.git
    targetRevision: HEAD
    path: k8s-deployment           # This points to the folder where manifests live
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated: {}
